### ISSUE TITLE
/onboarding -- contract-to-hire bounty

### ISSUE THREAD

**Issue by PeerRich** [solarpunk2077/solarpunk#2]
This project can lead to a part-time contract as the first fullstack dev
- two weeks max

Stack:
- typescript
- react/nextjs
- supabase (db, auth with magic email signin link)
- geoman.io
- google maps tile (not openstreetmap)
- shadcn/ui for UI
- resend for emails https://supabase.com/docs/guides/functions/examples/send-emails

Task:

https://solarpunk2077.com/onboarding

- Start wih an input with geosearch https://geoman.io/blog/using-geosearch-in-your-geoman-project
- open map immediately with "vertex" tool active:
<img width="633" alt="CleanShot 2024-06-21 at 10 47 13@2x" src="https://github.com/solarpunk2077/solarpunk/assets/8019099/29ee6bbe-8986-47e6-a663-eede035912fe">

- update right sidebar with all acres submitted
- ask for name + email
- submit form and send an email to us and a confirmation email to the user submitting 
  - the email confirmation can also include a "Sign in" link (supabase magic link if people want to check-in about their project) 
- bonus points: detect language of the submitted locations and send the email in the correct language
- after submitting the form, show a nice looking "Thank you for submitting your acres. We will be in touch with you within the next 24 hours"
- be able to log in afterwards with supabase magic-link with the users email
- logged in, you can see a 4 step Stepper (Details, In Review, Planning, Deployment) using https://shadcn-stepper.vercel.app/ 
  - Step 1 Details: Ask for more information, such as phone numbers, "Tell us more about your farm", Radio: Preferred Finance option (Financing myself, Financing with a loan for myself, Financed by Solarpunk)
  - Step 2: In Review: Just an EmptyScreen: "We are currently reviewing your application"

In our DB we should track every users step and we can update them manually in the beginning

Later:
  - Step 3: Planning: TBD
  - Step 4: Deployment: TBD

**Comment by PeerRich** [comment]
the contract to hire bounty is $2500. project has to be reasonably finished to qualify. we reserve the right to deem a project unfinished. max. 4 applicants

**Comment by abhijeetsingh-22** [comment]
I will be working on this !!

**Comment by CodeKage25** [comment]
I'm interested in working on this issue

**Comment by abhijeetsingh-22** [comment]
After creating PR, I saw that another PR was merged a few hrs before I created mine. 

Although I guess this PR #5 won’t be merged, I am keeping it open as my application to this task since only 2 PRs were created before it.

**Comment by PeerRich** [comment]
sorry i forgot to close
